/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electionserver.server;

import electionserver.server.model.Candidate;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author alysson
 */
public class ServerView extends javax.swing.JFrame {
    
    private ArrayList<Candidate> candidates = new ArrayList<>();
    
    /**
     * Creates new form ServerView
     */
    public ServerView() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        candidateForm = new javax.swing.JDialog();
        formAddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        candidateCodeField = new javax.swing.JTextField();
        candidateNameField = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidatesTable = new javax.swing.JTable();
        electionServerTitle = new javax.swing.JLabel();
        addCandidateButton = new javax.swing.JButton();
        deleteCandidate = new javax.swing.JButton();
        startVote = new javax.swing.JButton();

        candidateForm.setMinimumSize(new java.awt.Dimension(498, 347));
        candidateForm.setResizable(false);

        formAddButton.setText("Add");
        formAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formAddButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Candidate Code");

        jLabel2.setText("Candidate Name");

        javax.swing.GroupLayout candidateFormLayout = new javax.swing.GroupLayout(candidateForm.getContentPane());
        candidateForm.getContentPane().setLayout(candidateFormLayout);
        candidateFormLayout.setHorizontalGroup(
            candidateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, candidateFormLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(candidateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(candidateFormLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(formAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(candidateCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        candidateFormLayout.setVerticalGroup(
            candidateFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(candidateFormLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidateCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(formAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        candidatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Candidate Code", "Candidate Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(candidatesTable);
        if (candidatesTable.getColumnModel().getColumnCount() > 0) {
            candidatesTable.getColumnModel().getColumn(0).setResizable(false);
            candidatesTable.getColumnModel().getColumn(1).setResizable(false);
        }

        electionServerTitle.setFont(new java.awt.Font("Fira Sans Compressed SemiBold", 1, 24)); // NOI18N
        electionServerTitle.setText("ELECTION SERVER");

        addCandidateButton.setText("Add Candidate");
        addCandidateButton.setToolTipText("");
        addCandidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidateButtonActionPerformed(evt);
            }
        });

        deleteCandidate.setText("Delete Candidate");
        deleteCandidate.setToolTipText("");
        deleteCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCandidateActionPerformed(evt);
            }
        });

        startVote.setText("Start Vote");
        startVote.setToolTipText("");
        startVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startVoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electionServerTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startVote, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCandidateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(electionServerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCandidateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(deleteCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startVote, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCandidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidateButtonActionPerformed

        this.candidateForm.setVisible(true);
        
    }//GEN-LAST:event_addCandidateButtonActionPerformed

    private void deleteCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCandidateActionPerformed
        
        int[] selectedRows = this.candidatesTable.getSelectedRows();
        
        if(selectedRows.length <= 0) {
            
            this.jOptionPane1.showMessageDialog(this,
                    "Please, select one or more candidates on table",
                    "Delete candidate failed",
                    jOptionPane1.WARNING_MESSAGE);
            
        }else{
            
            for(int i = 0; i < selectedRows.length; i++) {
                
                int id = (Integer) this.candidatesTable.getValueAt(i, 0);
                
                if(id > 0){
                    for(int j = 0; j < this.candidates.size(); j++){
                        if(this.candidates.get(j).getId() == id){
                            this.candidates.remove(this.candidates.get(j));
                            break;
                        }
                    }
                } 
            }

           this.fillTable();
        }
       
    }//GEN-LAST:event_deleteCandidateActionPerformed

    private void startVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startVoteActionPerformed
       
        if(this.candidates.isEmpty()){
            
            this.jOptionPane1.showMessageDialog(this,
                    "Please, select one or more candidates on table",
                    "Delete candidate failed",
                    jOptionPane1.WARNING_MESSAGE);
            
        }else{
            
            try {
                new CalculationView(this.candidates).setVisible(true);
            } catch (RemoteException ex) {
                this.jOptionPane1.showMessageDialog(this,
                    ex.getMessage(),
                    "Server Start Failed",
                    jOptionPane1.WARNING_MESSAGE);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(ServerView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(ServerView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.dispose();
            
        }
        
        
    }//GEN-LAST:event_startVoteActionPerformed

    private void formAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formAddButtonActionPerformed
        
        int id = Integer.parseInt(this.candidateCodeField.getText());
        String name = this.candidateNameField.getText();

        Candidate candidate = new Candidate(id, name);
        
        this.candidates.add(candidate);
        
        this.fillTable();
        
        this.candidateForm.setVisible(false);
        
        this.candidateCodeField.setText("");
        this.candidateNameField.setText("");
        
    }//GEN-LAST:event_formAddButtonActionPerformed
    
    private void fillTable(){
        if(this.candidates.isEmpty()){
            
            for(int i = 0; i < this.candidatesTable.getRowCount(); i++) {
                this.candidatesTable.setValueAt("", i, 0);
                this.candidatesTable.setValueAt("", i, 1);
            } 
            
        }else{
           
            for(int i = 0; i < this.candidates.size(); i++) {
                this.candidatesTable.setValueAt(this.candidates.get(i).getId(), i, 0);
                this.candidatesTable.setValueAt(this.candidates.get(i).getName(), i, 1);
            } 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCandidateButton;
    private javax.swing.JTextField candidateCodeField;
    private javax.swing.JDialog candidateForm;
    private javax.swing.JTextField candidateNameField;
    private javax.swing.JTable candidatesTable;
    private javax.swing.JButton deleteCandidate;
    private javax.swing.JLabel electionServerTitle;
    private javax.swing.JButton formAddButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startVote;
    // End of variables declaration//GEN-END:variables
}
