/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package electionserver.client;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import electionserver.server.model.Candidate;
import java.net.MalformedURLException;

/**
 *
 * @author alysson
 */
public class ClientView extends javax.swing.JFrame {
    
    private Client client;
    
    private int candidateCode;
   
    /**
     * Creates new form UrnView
     */
    public ClientView() {
        initComponents();
        this.client = new Client();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        candidateNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmCandidateCode = new javax.swing.JTextField();
        confirmCandidateNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        voteButton = new javax.swing.JButton();
        candidateCodeField = new javax.swing.JTextField();
        candidateCodeLabel = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(450, 450));
        jDialog1.setResizable(false);

        candidateNameLabel.setText("Candidate Name");

        jLabel2.setText("Candidate Code");

        confirmCandidateCode.setEnabled(false);

        confirmCandidateNameField.setEnabled(false);

        cancelButton.setText("Cancel");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(candidateNameLabel)
                        .addComponent(confirmCandidateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(confirmCandidateCode, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmCandidateCode, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(candidateNameLabel)
                .addGap(18, 18, 18)
                .addComponent(confirmCandidateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        voteButton.setText("Vote");
        voteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteButtonActionPerformed(evt);
            }
        });

        candidateCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateCodeFieldActionPerformed(evt);
            }
        });

        candidateCodeLabel.setText("Candidate Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(candidateCodeLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(candidateCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(203, 203, 203))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(voteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(323, 323, 323)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(candidateCodeLabel)
                .addGap(18, 18, 18)
                .addComponent(candidateCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(voteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void candidateCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateCodeFieldActionPerformed
        
    }//GEN-LAST:event_candidateCodeFieldActionPerformed

    private void voteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteButtonActionPerformed
        
        if(this.client.getStub() == null) {
            try {
                this.client.connect();
            } catch (RemoteException | NotBoundException | IllegalCallerException ex) {
                this.jOptionPane1.showMessageDialog(this,
                    ex.getMessage(),
                    "Connect with server error",
                    jOptionPane1.WARNING_MESSAGE);
            } catch (MalformedURLException ex) {
                this.jOptionPane1.showMessageDialog(this,
                    ex.getMessage(),
                    "Connect with server error",
                    jOptionPane1.WARNING_MESSAGE);
            }
        }
        
        
        String candidateCode = this.candidateCodeField.getText();
       
        
        if(candidateCode.isBlank() || candidateCode.isEmpty()) {
            candidateCode = "0";
        }
            
        Candidate candidate = this.client.checkCandidate(Integer.parseInt(candidateCode));
        
        if(candidate != null) {
            this.confirmCandidateCode.setText(String.valueOf(candidate.getId()));
            this.confirmCandidateNameField.setText(candidate.getName());
            this.jDialog1.setVisible(true);
            this.candidateCode = candidate.getId();
        }else{
            this.confirmCandidateCode.setText("Blank vote");
            this.confirmCandidateNameField.setText("Blank vote");
            this.jDialog1.setVisible(true);
            this.candidateCode = 0;
        }
        
    }//GEN-LAST:event_voteButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        try {
            boolean result = this.client.processVote(this.candidateCode);
            
            if(result) {
                this.jDialog1.setVisible(false);
                this.jOptionPane1.showMessageDialog(this,
                    "Your vote has been process with success",
                    "Success",
                    jOptionPane1.INFORMATION_MESSAGE);
            }
        } catch (RemoteException ex) {
             this.jOptionPane1.showMessageDialog(this,
                    ex.getMessage(),
                    "error trying to process vote",
                    jOptionPane1.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField candidateCodeField;
    private javax.swing.JLabel candidateCodeLabel;
    private javax.swing.JLabel candidateNameLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField confirmCandidateCode;
    private javax.swing.JTextField confirmCandidateNameField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JButton voteButton;
    // End of variables declaration//GEN-END:variables
}
